### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by snegurova** [snegurova/homepage#9]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by innasn** [comment]
INNA SNEGUROVA
FRONT-END WEB DEVELOPER
— Hello! I am a novice front-end developer seeking to leverage skills in creating awesome apps such as CRM or ERP systems.
I have a great experience in management. It's more then 10 years, 4 of them with web-based projects and dispersed teams.
I think visually, so I prefer to plan projects with prototyping.

About me in three words - Client - Developer translator
